[package]
name = "oma"
version = "0.24.3"
edition = "2021"
description = "Omakase (oma) - package management interface for AOSC OS"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Debian
apt-sources-lists = { git = "https://github.com/pop-os/apt-sources-lists", rev = "0df4611ec7293010551f95659f28f1b1da9cc0c8" }
debcontrol = { git = "https://github.com/AOSC-Dev/debcontrol-rs/", rev = "e92376703b20afe1360f3612472f2597029c7475" }
rust-apt = { git = "https://gitlab.com/volian/rust-apt", rev = "c6d099ca50da3d3d8f28c6e80b01cd37005c6f94" }
# Cli
clap = { version = "4.2", features = ["cargo", "wrap_help",] }
dialoguer = "0.10"
tabled = { version = "0.10", features = ["color"] }
indicatif = "0.17"
console = "0.15"
# For Database, Packages Download
reqwest = "0.11"
tokio = { version = "1.15", default_features = false, features = ["rt", "fs", "io-util", "rt-multi-thread"] }
futures = "0.3"
# For log
tracing = "0.1"
tracing-subscriber = "0.3"
os-release = "0.1"
time = { version = "0.3", features = ["local-offset", "macros"] }
# For read and verify database
xz2 = "0.1"
sequoia-openpgp = "1.13"
flate2 = "1.0"
hex = "0.4"
sha2 = "0.10"
# For Search package
glob-match = "0.2"
strsim = "0.10"
# For read AOSC OS MIRROR file
serde_yaml = "0.9"
# For oma provides/list-files
regex = "1.7"
grep = "0.2"
# Other Dependencies
fs4 = "0.6"
sysinfo = "0.28"
anyhow = "1.0" 
nix = "0.26"
serde = { version = "1.0", features = ["derive"] }
which = "4.4"
serde_json = "1.0"
ctrlc = "3.2"
thiserror = "1.0"
once_cell = "1.17"

[build-dependencies]
clap_mangen = "0.2.10"
clap = { version = "4.2", features = ["cargo", "wrap_help"] }
