[package]
name = "oma"
version = "0.45.1"
edition = "2021"
description = "Omakase (oma) - Package management interface for AOSC OS"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Debian
apt-sources-lists = { git = "https://github.com/pop-os/apt-sources-lists", rev = "0df4611ec7293010551f95659f28f1b1da9cc0c8" }
debcontrol = { git = "https://github.com/AOSC-Dev/debcontrol-rs/", rev = "e92376703b20afe1360f3612472f2597029c7475" }
rust-apt = { git = "https://gitlab.com/volian/rust-apt", rev = "576f0aed20791121189e145c5965b079382203ca" }
# Cli
clap = { version = "4.2.4", features = ["cargo", "wrap_help", "color"] }
dialoguer = "0.10"
tabled = { version = "0.12", features = ["color"] }
indicatif = "0.17"
console = { version = "0.15", features = ["unicode-width"] }
inquire = { git = "https://github.com/AOSC-Dev/inquire", rev = "3230e6daefb71e335764d901d1c6d3a5e706312e", optional = true }
# For Database, Packages Download
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.15", default_features = false, features = ["rt", "fs", "io-util", "rt-multi-thread"] }
futures = "0.3"
futures-util = "0.3"
# For log
tracing = "0.1"
tracing-subscriber = "0.3"
os-release = "0.1"
time = { version = "0.3", features = ["local-offset", "macros", "parsing"] }
# For read and verify database
xz2 = "0.1"
sequoia-openpgp = "1.13"
flate2 = { version = "1.0", features = ["zlib-ng"], default-features = false  }
hex = "0.4"
sha2 = "0.10"
# For Search package
glob-match = "0.2"
strsim = "0.10"
indicium = "0.4"
# For read AOSC OS MIRROR file
serde_yaml = "0.9"
# For oma provides/list-files
regex = "1.7"
grep = "0.2"
# For config
toml = "0.7"
# Other Dependencies
fs4 = "0.6"
sysinfo = "0.29"
anyhow = "1.0" 
nix = "0.26"
serde = { version = "1.0", features = ["derive"] }
which = "4.4"
serde_json = "1.0"
ctrlc = "3.2"
thiserror = "1.0"
once_cell = "1.17"
indexmap = {version = "1.9", features = ["serde-1"], optional = true }
url-escape = "0.1"

# i18n
i18n-embed = { version = "0.13", features = ["fluent-system", "desktop-requester"]}
i18n-embed-fl = "0.6"
rust-embed = "^6"
unic-langid = "0.9"

[build-dependencies]
clap_mangen = "0.2.10"
clap_complete = "4.2"
clap = { version = "4.2.4", features = ["cargo", "wrap_help", "color"] }

[features]
aosc = ["indexmap", "inquire"]
default  = ["aosc"]
