[package]
name = "oma"
version = "0.15.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apt-sources-lists = { git = "https://github.com/pop-os/apt-sources-lists", rev = "0df4611ec7293010551f95659f28f1b1da9cc0c8" }
anyhow = "1.0" 
nix = "0.26"
reqwest = "0.11"
log = "0.4"
debcontrol = { git = "https://github.com/AOSC-Dev/debcontrol-rs/", rev = "e92376703b20afe1360f3612472f2597029c7475" }
serde = { version = "1.0", features = ["derive"] }
xz2 = "0.1"
sequoia-openpgp = "1.13"
sha2 = "0.10"
flate2 = "1.0"
rust-apt = { git = "https://gitlab.com/volian/rust-apt", rev = "496511ad09ca8f997df28dd1d38971977ed2680d" }
clap = { version = "4.1", features = ["derive"] }
indicatif = "0.17"
console = "0.15"
tokio = { version = "1.15", default_features = false, features = ["rt", "macros", "fs", "io-util", "rt-multi-thread"] }
futures = "0.3"
serde_yaml = "0.9"
hex = "0.4"
tabled = { version = "0.10", features = ["color"] }
glob-match = "0.2"
strsim = "0.10"
grep = "0.2"
which = "4.4"
serde_json = "1.0"
regex = "1.7"
sysinfo = "0.28"
ctrlc = "3.2"
dialoguer = "0.10"
fs4 = "0.6"
thiserror = "1.0"
time = { version = "0.3", features = ["local-offset"] }
once_cell = "1.17"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
os-release = "0.1"
