[package]
name = "oma"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apt-sources-lists = { git = "https://github.com/pop-os/apt-sources-lists", rev = "0df4611ec7293010551f95659f28f1b1da9cc0c8" }
anyhow = "1.0" 
nix = "0.26"
reqwest = { version = "0.11", features = ["blocking"] }
log = "0.4"
env_logger = "0.10"
debcontrol = "0.1"
lazy_static = "1.4"
nom = "7.1"
serde = { version = "1.0", features = ["derive"] }
xz2 = "0.1"
sequoia-openpgp = "1.13"
sha2 = "0.10"
flate2 = "1.0"
indexmap = "1.9"
rust-apt = { git = "https://gitlab.com/volian/rust-apt", rev = "6a8146e47a755ff7e219d0bc28fc1fe2161b044b" }
clap = { version = "4.1", features=["derive"] }
indicatif = "0.17"
console = "0.15"
tokio = { version = "1.15", default_features = false, features = ["rt", "macros", "fs", "io-util"] }
futures = "0.3"
serde_yaml = "0.9"
hex = "0.4"
tabled = { version = "0.10", features = ["color"] }
glob-match = "0.2"
