[package]
name = "oma"
version = "1.0.8"
edition = "2021"
description = "Omakase (oma) - Package management interface for AOSC OS"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Cli
clap = { version = "4.2.4", features = ["cargo", "wrap_help", "color"] }
once_cell = "1.18"
nix = "0.26"
anyhow = "1.0"
ctrlc = "3.4"
tabled = { version = "0.14", features = ["color"] }
dialoguer = "0.10"
tokio = { version = "1.15", default_features = false, features = ["rt", "fs", "io-util", "rt-multi-thread", "macros"] }
derive_builder = "0.12.0"
reqwest = "0.11"
oma-utils = { path = "./oma-utils" }
oma-console = { path = "./oma-console" }
oma-pm = { path = "./oma-pm" }
oma-refresh = { path = "./oma-refresh", features = ["aosc"] }
oma-contents = { path = "./oma-contents" }
oma-fetch = { path = "./oma-fetch" }
oma-topics = { path = "./oma-topics", optional = true }
oma-inquire = "0.1"

# i18n
i18n-embed = { version = "0.13", features = ["fluent-system", "desktop-requester"]}
i18n-embed-fl = "0.6"
rust-embed = "^6"
unic-langid = "0.9"

[build-dependencies]
clap_mangen = "0.2.10"
clap_complete = "4.2"
clap = { version = "4.2.4", features = ["cargo", "wrap_help", "color"] }

[features]
aosc = ["oma-topics"]
default  = ["aosc"]

[workspace]
members = ["oma-contents", "oma-console", "oma-topics", "oma-fetch", "oma-refresh", "oma-utils", "oma-pm"]
