[package]
name = "oma-topics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.18"
indexmap = {version = "2.0", features = ["serde"] }
apt-sources-lists = { git = "https://github.com/pop-os/apt-sources-lists", rev = "0df4611ec7293010551f95659f28f1b1da9cc0c8" }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.28", default_features = false, features = ["rt", "fs", "io-util", "rt-multi-thread", "macros"] }
thiserror = "1.0"
futures = "0.3"
oma-console = { path = "../oma-console" }

[dev-dependencies]
oma-inquire = "0.1"
oma-console = { path = "../oma-console" }
