[package]
name = "oma-pm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-apt = { git = "https://gitlab.com/volian/rust-apt", rev = "576f0aed20791121189e145c5965b079382203ca" }
thiserror = "1.0"
time = { version = "0.3", features = ["local-offset", "macros", "parsing"] }
glob-match = "0.2"
indicium = "0.4"
oma-utils = { path = "../oma-utils" }
url-escape = "0.1"
oma-fetch = { path = "../oma-fetch" }
tokio = { version = "1.15", default_features = false, features = ["rt", "fs", "io-util", "rt-multi-thread", "macros"] }
oma-console = { path = "../oma-console" }
derive_builder = "0.12"
fs4 = "0.6"
anyhow = "1.0"
