[package]
name = "oma-pm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-apt = { git = "https://gitlab.com/volian/rust-apt", rev = "576f0aed20791121189e145c5965b079382203ca" }
thiserror = "1.0"
tracing = "0.1"
time = { version = "0.3", features = ["local-offset", "macros", "parsing"] }
glob-match = "0.2"
indicium = "0.4"
oma-utils = { path = "../oma-utils" }
