[package]
name = "oma-pm"
version = "0.2.0"
edition = "2021"
description = "A crate to help oma handle package manager operation"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oma-apt = "0.1"
thiserror = "1.0"
time = { version = "0.3", features = ["local-offset", "macros", "parsing"] }
glob-match = "0.2"
indicium = "0.4"
oma-utils = { version = "^0.1.1", path = "../oma-utils", features = ["human-bytes"] }
url-escape = "0.1"
oma-fetch = { version = "^0.1.1", path = "../oma-fetch" }
tokio = { version = "1.15", default_features = false, features = [
    "rt",
    "fs",
    "io-util",
    "rt-multi-thread",
    "macros",
] }
oma-console = { version = "0.1", path = "../oma-console" }
derive_builder = "0.12"
fs4 = "0.6"
anyhow = "1.0"
once_cell = "1.18"
serde = { version = "1.0", features = ["derive"] }
