[package]
name = "oma-utils"
version = "0.1.1"
edition = "2021"
description = "Some small-tools to help oma handle something"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
number_prefix = "0.4"
once_cell = "1.18"
os-release = "0.1"
oma-console = { version = "0.1.0", path = "../oma-console" }
zbus = "3.14"
