[package]
name = "oma-contents"
version = "0.1.1"
edition = "2021"
description = "Omakase (oma) contents tool to help oma handle apt database contents"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grep = "0.2"
serde = "1.0"
regex = "1.8"
chrono = "0.4"
which ="4.4"
serde_json = "1.0"
strsim = "0.10"
thiserror = "1.0"
oma-console = { version = "^0.1.1", path = "../oma-console" }

[dev-dependencies]
indicatif = "0.17"
oma-utils = { path = "../oma-utils", features = ["dpkg"]}
