[package]
name = "oma-contents"
version = "0.2.0"
edition = "2021"
description = "Omakase (oma) contents tool to help oma handle apt database contents"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grep = "0.2"
regex = "1.8"
chrono = "0.4"
which ="4.4"
strsim = "0.10"
thiserror = "1.0"
winnow = "0.5"

[dev-dependencies]
indicatif = "0.17"
oma-utils = { path = "../oma-utils", features = ["dpkg"]}

[features]
aosc = []
default = ["aosc"]