[package]
name = "oma-contents"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grep = "0.2"
serde = "1.0"
time = "0.3"
regex = "1.8"
which ="4.4"
serde_json = "1.0"
strsim = "0.10"
thiserror = "1.0"

[dev-dependencies]
indicatif = "0.17"
