[package]
name = "oma-refresh"
version = "0.3.0"
edition = "2021"
description = "A crate to help oma refresh apt repo database"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oma-fetch = { path = "../oma-fetch" }
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
url = "2.3"
tokio = { version = "1.28", default_features = false, features = ["fs"] }
serde_yaml = "0.9"
once_cell = "1.18"
futures = "0.3"
oma-apt-sources-lists = "0.1"
oma-debcontrol = "0.3"
sequoia-openpgp = "1.13"
anyhow = "1.0"
chrono = { version = "0.4", features = ["unstable-locales"] }
oma-topics = { path = "../oma-topics", optional = true }
reqwest = "0.11"
oma-utils = { version = "^0.1.5", path = "../oma-utils", features = ["dpkg"] }
oma-console = { path = "../oma-console" }

[features]
aosc = ["oma-topics"]
default = ["aosc"]

[dev-dependencies]
tokio = { version = "1.28", default_features = false, features = ["macros", "rt-multi-thread"] }
indicatif = "0.17"
dashmap = "5.5"
