[package]
name = "oma-console"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.15"
thiserror = "1.0"
indicatif = "0.17"
once_cell = "1.18"
