[package]
name = "oma-pm-operation-type"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "some type abstract from oma-pm crate"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_builder = "0.20"
serde = { version = "1.0", features = ["derive"] }
oma-utils = { version = "^0.8.0", path = "../oma-utils", features = [
    "human-bytes",
] }
