[package]
name = "oma-fetch"
version = "0.1.2"
edition = "2021"
description = "A downloader to help oma download something"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
reqwest = "0.11"
tokio = { version = "1.28", default_features = false, features = ["fs"] }
serde = { version = "1.0", features = ["derive"] }
hex = "0.4"
sha2 = "0.10"
futures = "0.3"
oma-console = { version = "^0.1.1", path = "../oma-console" }
derive_builder = "0.12"
async-compression = { version = "0.4", features = ["tokio", "gzip", "xz"] }

# i18n
i18n-embed = { version = "0.13", features = ["fluent-system", "desktop-requester"]}
i18n-embed-fl = "0.6"
rust-embed = "^6"
unic-langid = "0.9"
once_cell = "1.18"

[dev-dependencies]
tokio = { version = "1.28", default-features = false, features = ["macros", "rt-multi-thread"] }
